### ISSUE TITLE
Connect to remote DB

### ISSUE THREAD

**Issue by stephencweiss** [HRR34-SDC05/ProductDescription#13]
Migrating DB from local machine to AWS will require refactoring for the database. 

- [x] Update connectPG
- [x] Confirm app still runs locally
- [x] Run a sample seed process from local to remote DB
- [ ] Migrate to remote environment and test again.

**Comment by stephencweiss** [comment]
Right now the issue *appears* to be the configuration of the PSQL EC2 instance. I'm able to log in and have a database, but it's not accepting calls from my local machine. 

Confusing part is that, like [this](https://stackoverflow.com/questions/15934364/psql-server-closed-the-connection-unexepectedly) article mentions, I've tweaked the `pg_hba.conf` and `postgresql.conf` files.

![image](https://user-images.githubusercontent.com/39878535/49200517-087bd080-f352-11e8-8a25-724dfbf07a8d.png)

![image](https://user-images.githubusercontent.com/39878535/49200527-116ca200-f352-11e8-8f0c-a1db2ae5ad73.png)

The error I'm getting is the following:
```
(node:19849) UnhandledPromiseRejectionWarning: Error: Connection terminated unexpectedly
    at Connection.con.once (/Users/Stephen/Documents/_coding/hackReactorRemote/hrr34-sdc/ProductDescription/node_modules/pg/lib/client.js:200:9)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/Users/Stephen/Documents/_coding/hackReactorRemote/hrr34-sdc/ProductDescription/node_modules/pg/lib/connection.js:129:10)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:19849) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19849) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:19849) UnhandledPromiseRejectionWarning: RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: Could not complete GET request to Database
    at ServerResponse.writeHead (_http_server.js:208:11)
    at ServerResponse._implicitHeader (_http_server.js:199:8)
    at write_ (_http_outgoing.js:585:9)
    at ServerResponse.end (_http_outgoing.js:709:5)
    at ServerResponse.send (/Users/Stephen/Documents/_coding/hackReactorRemote/hrr34-sdc/ProductDescription/node_modules/express/lib/response.js:221:10)
    at ServerResponse.json (/Users/Stephen/Documents/_coding/hackReactorRemote/hrr34-sdc/ProductDescription/node_modules/express/lib/response.js:267:15)
    at ServerResponse.send (/Users/Stephen/Documents/_coding/hackReactorRemote/hrr34-sdc/ProductDescription/node_modules/express/lib/response.js:158:21)
    at postgreSQL.query.then.catch (/Users/Stephen/Documents/_coding/hackReactorRemote/hrr34-sdc/ProductDescription/server/index.js:62:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19849) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by stephencweiss** [comment]
Solution: After updating the `pg_hba.conf` and `postgresql.conf` files, needed to run `sudo service postgresql restart` to allow the changes to stick.
